services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dernek
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  # minio:
  #   image: minio/minio:latest
  #   command: server /data --console-address ":9001"
  #   restart: unless-stopped
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   ports:
  #     - "9000:9000" # S3 API
  #     - "9001:9001" # Console UI
  #   volumes:
  #     - minio-data:/data
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
volumes:
  db-data:
  # minio-data:
